In [458]:
import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\NAME AVG ROUNDS YEAR.csv'

# Cargar el archivo CSV en un DataFrame
data_frame = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frame.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,AVG,TOTAL STROKES,TOTAL ADJUSTMENT,TOTAL ROUNDS
0,1,0,46970,Jon Rahm,69.300,5316,20.067,77
1,2,0,30925,Dustin Johnson,69.619,5011,1.597,72
2,3,0,26329,Louis Oosthuizen,69.714,5159,- .200,74
3,4,0,47959,Bryson DeChambeau,69.728,5566,12.233,80
4,5,0,35450,Patrick Cantlay,69.736,5413,26.413,78

In [459]:
# Agregar la columna "YEAR" con el valor "2020"
data_frame['YEAR'] = 2020

In [460]:
# Seleccionar solo las columnas que deseas mantener
columns_to_keep = ['PLAYER_ID', 'PLAYER', 'AVG', 'TOTAL ROUNDS', 'YEAR']
data_frame = data_frame.loc[:, columns_to_keep]

In [461]:
data_frame.head()

   PLAYER_ID             PLAYER     AVG  TOTAL ROUNDS  YEAR
0      46970           Jon Rahm  69.300            77  2020
1      30925     Dustin Johnson  69.619            72  2020
2      26329   Louis Oosthuizen  69.714            74  2020
3      47959  Bryson DeChambeau  69.728            80  2020
4      35450    Patrick Cantlay  69.736            78  2020

In [462]:
# Ahora vamos ir cargando diferentes DF y vamos a ir ensamblando por a√±o las estafisticas que necesitamos

# Primero voy a ir poniendo nombres a las columnas para que no haya confusiones

data_frame.rename(columns={'AVG': 'AVG_TOTAL_FOR_ROUND'}, inplace=True)
data_frame.rename(columns={'PLAYER': 'PLAYER_NAME'}, inplace=True)
data_frame.rename(columns={'TOTAL ROUNDS': 'TOTAL_ROUNDS'}, inplace=True)

In [463]:
data_frame.head()

   PLAYER_ID        PLAYER_NAME  AVG_TOTAL_FOR_ROUND  TOTAL_ROUNDS  YEAR
0      46970           Jon Rahm               69.300            77  2020
1      30925     Dustin Johnson               69.619            72  2020
2      26329   Louis Oosthuizen               69.714            74  2020
3      47959  Bryson DeChambeau               69.728            80  2020
4      35450    Patrick Cantlay               69.736            78  2020

In [464]:
# VAMOS A INCORPORAR LA ESTADISTICA AVG DRIVER DISTANCE

In [465]:
import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\DRIVING DISTANCE AVG 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameDD = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameDD.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,AVG,TOTAL DISTANCE,TOTAL DRIVES
0,1,0,47959,Bryson DeChambeau,323.7,51790,160
1,2,0,28237,Rory McIlroy,319.3,47252,148
2,3,0,52372,Cameron Champ,317.1,47568,150
3,4,0,56278,Matthew Wolff,315.9,34748,110
4,5,0,56762,Will Gordon,315.0,55434,176

In [466]:
data_frameDD = data_frameDD[['PLAYER_ID', 'AVG']]

In [467]:
data_frameDD.rename(columns={'AVG': 'AVG_DRIVER_DISTANCE'}, inplace=True)

In [468]:
data_frameDD.head()

   PLAYER_ID  AVG_DRIVER_DISTANCE
0      47959                323.7
1      28237                319.3
2      52372                317.1
3      56278                315.9
4      56762                315.0

In [469]:
# ENSAMBLAMOS EL DRIVER DISTANCE DENTRO DEL DATA FRAME INICIAL

data_frame = data_frame.merge(data_frameDD, on='PLAYER_ID', how='left')

In [470]:
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE
0,46970,Jon Rahm,69.300,77,2020,309.0
1,30925,Dustin Johnson,69.619,72,2020,312.9
2,26329,Louis Oosthuizen,69.714,74,2020,297.8
3,47959,Bryson DeChambeau,69.728,80,2020,323.7
4,35450,Patrick Cantlay,69.736,78,2020,302.8

In [471]:
# VAMOS A INCORPORAR LA ESTADISTICA AVG FAIRWAY PERCENTAJE

In [472]:
import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\FAIRWAY PERCENTAJE.csv'

# Cargar el archivo CSV en un DataFrame
data_frameFP = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameFP.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,%,FAIRWAYS HIT,POSSIBLE FAIRWAYS,RELATIVE TO PAR
0,1,0,30927,Brendon Todd,75.15,747,994,-0.18
1,2,0,26476,Chez Reavie,74.50,739,992,-0.16
2,3,0,31560,Brian Stuard,73.67,901,1223,-0.15
3,4,0,19803,Ryan Armour,73.39,684,932,-0.18
4,5,0,45526,Abraham Ancer,71.04,802,1129,-0.22

In [473]:
data_frameFP.rename(columns={'%': 'AVG_FAIRWAY'}, inplace=True)

In [474]:
data_frameFP = data_frameFP[['PLAYER_ID', 'AVG_FAIRWAY']]

In [475]:
# ENSAMBLAMOS EL DRIVER DISTANCE DENTRO DEL DATA FRAME INICIAL

data_frame = data_frame.merge(data_frameFP, on='PLAYER_ID', how='left')

In [476]:
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21

In [477]:
# VAMOS A INCORPORAR LA ESTADISTICA PEDEX POINTS

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\FEDEX 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameFPOINTS = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameFPOINTS.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,POINTS,# OF WINS,# OF TOP 10'S,POINTS BEHIND LEAD
0,1,0,50525,Collin Morikawa,2171,2,8,0.0
1,2,0,34046,Jordan Spieth,2139,1,9,32.0
2,3,0,35450,Patrick Cantlay,2056,2,5,115.0
3,4,0,34099,Harris English,2039,2,8,132.0
4,5,0,46970,Jon Rahm,2003,1,12,168.0

In [478]:
data_frameFPOINTS.rename(columns={'POINTS': 'FEDEX_POINTS'}, inplace=True)

In [479]:
data_frameFPOINTS = data_frameFPOINTS[['PLAYER_ID', 'FEDEX_POINTS']]

In [480]:
# ENSAMBLAMOS EL DRIVER DISTANCE DENTRO DEL DATA FRAME INICIAL

data_frame = data_frame.merge(data_frameFPOINTS, on='PLAYER_ID', how='left')

In [481]:
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0

In [482]:
# VAMOS A INCORPORAR LA ESTADISTICA GREEN IN REGULATIONS

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\GIR 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameGIR = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameGIR.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,%,GREENS HIT,# HOLES,RELATIVE/PAR
0,1,0,22056,Cameron Percy,72.58,1006,1386,-0.25
1,2,0,46970,Jon Rahm,71.93,997,1386,-0.34
2,3,0,31646,Emiliano Grillo,71.47,1235,1728,-0.29
3,4,0,36871,Matthew NeSmith,71.09,1126,1584,-0.25
4,5,0,48045,Michael Gellerman,70.80,599,846,-0.22

In [483]:
data_frameGIR.rename(columns={'%': 'AVG_GIR'}, inplace=True)

In [484]:
data_frameGIR = data_frameGIR[['PLAYER_ID', 'AVG_GIR']]

In [485]:
# ENSAMBLAMOS EL GIR DENTRO DEL DATA FRAME INICIAL

data_frame = data_frame.merge(data_frameGIR, on='PLAYER_ID', how='left')

In [486]:
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16

In [487]:
# VAMOS A INCORPORAR LA ESTADISTICA MONEY

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\MONEY 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameMO = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameMO.head()

   RANK  MOVEMENT  PLAYER_ID             PLAYER     MONEY  YTD VICTORIES
0     1         0      46970           Jon Rahm  $7705933            1.0
1     2         0      35450    Patrick Cantlay  $7638805            4.0
2     3         0      47959  Bryson DeChambeau  $7426415            2.0
3     4         0      50525    Collin Morikawa  $7059908            2.0
4     5         0      33448      Justin Thomas  $6537153            1.0

In [488]:
data_frameMO = data_frameMO[['PLAYER_ID', 'MONEY']]

In [489]:
# ENSAMBLAMOS 

data_frame = data_frame.merge(data_frameMO, on='PLAYER_ID', how='left')

In [490]:
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805

In [491]:
# VAMOS A INCORPORAR LA ESTADISTICA DE PARES 3

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\P3 AVG 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameP3 = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameP3.head()

   RANK  MOVEMENT  PLAYER_ID         PLAYER STATUS  PAR 3 AVG  TOTAL PAR
0     1         0      20229   Stewart Cink    -14       2.96       1074
1     2         0      46970       Jon Rahm    -12       2.96        924
2     3         0      22056  Cameron Percy    -10       2.97        930
3     4         0      40026  Daniel Berger     -6       2.98       1008
4     4         0      36801   Mark Hubbard     -6       2.98       1182

In [492]:
data_frameP3.rename(columns={'PAR 3 AVG': 'PAR_3_AVG'}, inplace=True)
data_frameP3 = data_frameP3[['PLAYER_ID', 'PAR_3_AVG']]

In [493]:
# ENSAMBLAMOS 

data_frame = data_frame.merge(data_frameP3, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05

In [494]:
# VAMOS A INCORPORAR LA ESTADISTICA DE PARES 4

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\P4 AVG 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameP4 = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameP4.head()

   RANK  MOVEMENT  PLAYER_ID           PLAYER  STATUS  PAR 4 AVG  TOTAL PAR
0     1         0      31646  Emiliano Grillo     -44       3.96       4088
1     2         0      35450  Patrick Cantlay     -43       3.95       3328
2     3         0      45526    Abraham Ancer     -38       3.96       4192
3     4         0      40026    Daniel Berger     -36       3.96       3624
4     5         0      30926       Chris Kirk     -35       3.96       3680

In [495]:
data_frameP4.rename(columns={'PAR 4 AVG': 'PAR_4_AVG'}, inplace=True)
data_frameP4 = data_frameP4[['PLAYER_ID', 'PAR_4_AVG']]

# ENSAMBLAMOS 

data_frame = data_frame.merge(data_frameP4, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG,PAR_4_AVG
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96,3.96
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01,3.99
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05,3.98
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03,3.99
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05,3.95

In [496]:
# VAMOS A INCORPORAR LA ESTADISTICA DE PARES 5

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\P5 AVG 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameP5 = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameP5.head()

   RANK  MOVEMENT  PLAYER_ID             PLAYER  STATUS  PAR 5 AVG  TOTAL PAR
0     1         0      39971         Sungjae Im    -174       4.57       2020
1     2         0      46046  Scottie Scheffler    -152       4.55       1690
2     3         0      34099     Harris English    -150       4.49       1460
3     4         0      45486    Joaquin Niemann    -147       4.54       1590
4     4         0      46970           Jon Rahm    -147       4.46       1350

In [497]:
data_frameP5.rename(columns={'PAR 5 AVG': 'PAR_5_AVG'}, inplace=True)
data_frameP5 = data_frameP5[['PLAYER_ID', 'PAR_5_AVG']]

# ENSAMBLAMOS 

data_frame = data_frame.merge(data_frameP5, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG,PAR_4_AVG,PAR_5_AVG
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96,3.96,4.46
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01,3.99,4.54
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05,3.98,4.54
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03,3.99,4.45
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05,3.95,4.52

In [498]:
# VAMOS A INCORPORAR LA ESTADISTICA DE PUTT AVERAGE

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\PUTT AVG 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_framePAVG = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_framePAVG.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,AVG,GIR PUTTS,GREENS HIT,BIRDIE CONVERSION
0,1,0,35891,Cameron Smith,1.689,1638,970,37.47
1,2,0,32757,Patton Kizzire,1.707,2123,1244,34.11
2,3,0,34046,Jordan Spieth,1.708,1747,1023,36.06
3,4,0,33597,Harry Higgs,1.709,1567,917,35.27
4,5,0,47504,Sam Burns,1.710,1753,1025,35.59

In [499]:
data_framePAVG.rename(columns={'AVG': 'AVG_PUTT'}, inplace=True)

In [500]:
data_framePAVG = data_framePAVG[['PLAYER_ID', 'AVG_PUTT']]

In [501]:
# ENSAMBLAMOS EL AVG_PUTT DENTRO DEL DF INICIAL

data_frame = data_frame.merge(data_framePAVG, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG,PAR_4_AVG,PAR_5_AVG,AVG_PUTT
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96,3.96,4.46,1.733
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01,3.99,4.54,1.720
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05,3.98,4.54,1.747
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03,3.99,4.45,1.740
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05,3.95,4.52,1.746

In [502]:
# VAMOS A INCORPORAR LA ESTADISTICA SCRAMBLING PROMEDIO

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\SCAVG 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameSCAVG = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameSCAVG.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,%,PAR OR BETTER,MISSED GIR
0,1,0,35450,Patrick Cantlay,67.30,282,419
1,2,0,28252,Seamus Power,65.96,219,332
2,3,0,21961,Charles Howell III,65.86,272,413
3,4,0,25396,Kevin Na,65.12,366,562
4,5,0,29221,Webb Simpson,64.95,265,408

In [503]:
data_frameSCAVG.rename(columns={'%': 'AVG_SCRAMBLING'}, inplace=True)
data_frameSCAVG = data_frameSCAVG[['PLAYER_ID', 'AVG_SCRAMBLING']]

In [504]:
# ENSAMBLAMOS EL AVG_PUTT DENTRO DEL DF INICIAL

data_frame = data_frame.merge(data_frameSCAVG, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG,PAR_4_AVG,PAR_5_AVG,AVG_PUTT,AVG_SCRAMBLING
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96,3.96,4.46,1.733,62.98
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01,3.99,4.54,1.720,59.95
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05,3.98,4.54,1.747,63.81
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03,3.99,4.45,1.740,59.20
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05,3.95,4.52,1.746,67.30

In [505]:
# VAMOS A INCORPORAR LA ESTADISTICA STROKES GAINED APPROACH THE GREEN 

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\SG APP 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameSGAPP = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameSGAPP.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,AVG,TOTAL SG:APP,MEASURED ROUNDS
0,1,0,50525,Collin Morikawa,1.170,77.191,66
1,2,0,25364,Paul Casey,0.895,51.920,58
2,3,0,33448,Justin Thomas,0.887,60.283,68
3,4,0,33141,Keegan Bradley,0.856,66.749,78
4,5,0,40026,Daniel Berger,0.834,60.915,73

In [506]:
data_frameSGAPP.rename(columns={'AVG': 'AVG_SG_APPROACH'}, inplace=True)
data_frameSGAPP = data_frameSGAPP[['PLAYER_ID', 'AVG_SG_APPROACH']]

In [507]:
# ENSAMBLAMOS EL AVG_SG_APPROACH DENTRO DEL DF INICIAL

data_frame = data_frame.merge(data_frameSGAPP, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG,PAR_4_AVG,PAR_5_AVG,AVG_PUTT,AVG_SCRAMBLING,AVG_SG_APPROACH
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96,3.96,4.46,1.733,62.98,0.717
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01,3.99,4.54,1.720,59.95,0.315
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05,3.98,4.54,1.747,63.81,0.459
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03,3.99,4.45,1.740,59.20,0.291
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05,3.95,4.52,1.746,67.30,0.486

In [508]:
# VAMOS A INCORPORAR LA ESTADISTICA STROKES GAINED ARROUND THE GREEN

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\SG ATG 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameSGATG = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameSGATG.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,AVG,TOTAL SG:ARG,MEASURED ROUNDS
0,1,0,25396,Kevin Na,0.702,54.767,78
1,2,0,32139,Danny Willett,0.518,14.514,28
2,3,0,28679,Fabi√°n G√≥mez,0.484,16.456,34
3,4,0,37455,Si Woo Kim,0.467,38.757,83
4,5,0,28252,Seamus Power,0.440,18.463,42

In [509]:
data_frameSGATG.rename(columns={'AVG': 'AVG_SG_ATG'}, inplace=True)
data_frameSGATG = data_frameSGATG[['PLAYER_ID', 'AVG_SG_ATG']]

In [510]:
# ENSAMBLAMOS EL AVG_SG_ATG DENTRO DEL DF INICIAL

data_frame = data_frame.merge(data_frameSGATG, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG,PAR_4_AVG,PAR_5_AVG,AVG_PUTT,AVG_SCRAMBLING,AVG_SG_APPROACH,AVG_SG_ATG
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96,3.96,4.46,1.733,62.98,0.717,0.216
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01,3.99,4.54,1.720,59.95,0.315,0.147
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05,3.98,4.54,1.747,63.81,0.459,0.353
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03,3.99,4.45,1.740,59.20,0.291,-0.085
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05,3.95,4.52,1.746,67.30,0.486,0.363

In [511]:
# VAMOS A INCORPORAR LA ESTADISTICA STROKES GAINED ARROUND THE GREEN

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\SG PUTT 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameSPUTT = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameSPUTT.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,AVG,TOTAL SG:PUTTING,MEASURED ROUNDS
0,1,0,26329,Louis Oosthuizen,0.764,45.852,60
1,2,0,49771,J.T. Poston,0.706,55.768,79
2,3,0,24138,Ian Poulter,0.695,38.241,55
3,4,0,34360,Patrick Reed,0.669,44.154,66
4,5,0,24024,Zach Johnson,0.667,50.655,76

In [512]:
data_frameSPUTT.rename(columns={'AVG': 'AVG_SG_PUTTING'}, inplace=True)
data_frameSPUTT = data_frameSPUTT[['PLAYER_ID', 'AVG_SG_PUTTING']]

In [513]:
# ENSAMBLAMOS EL AVG_SG_ATG DENTRO DEL DF INICIAL

data_frame = data_frame.merge(data_frameSPUTT, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG,PAR_4_AVG,PAR_5_AVG,AVG_PUTT,AVG_SCRAMBLING,AVG_SG_APPROACH,AVG_SG_ATG,AVG_SG_PUTTING
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96,3.96,4.46,1.733,62.98,0.717,0.216,0.331
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01,3.99,4.54,1.720,59.95,0.315,0.147,0.429
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05,3.98,4.54,1.747,63.81,0.459,0.353,0.764
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03,3.99,4.45,1.740,59.20,0.291,-0.085,0.456
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05,3.95,4.52,1.746,67.30,0.486,0.363,0.402

In [514]:
# VAMOS A INCORPORAR LA ESTADISTICA STROKES GAINED TOTAL

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\SG TOTAL 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameSGTOT = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameSGTOT.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,AVG,TOTAL SG:T,TOTAL SG:T2G,TOTAL SG:P,MEASURED ROUNDS
0,1,0,46970,Jon Rahm,2.098,134.286,113.113,21.174,64
1,2,0,47959,Bryson DeChambeau,1.823,123.959,92.967,30.993,68
2,3,0,35450,Patrick Cantlay,1.820,123.758,96.411,27.349,68
3,4,0,26329,Louis Oosthuizen,1.599,95.967,50.115,45.852,60
4,5,0,48081,Xander Schauffele,1.484,93.464,63.250,30.215,63

In [515]:
data_frameSGTOT.rename(columns={'AVG': 'AVG_SG_TOTAL'}, inplace=True)
data_frameSGTOT = data_frameSGTOT[['PLAYER_ID', 'AVG_SG_TOTAL']]

In [516]:
# ENSAMBLAMOS EL AVG_SG_ATG DENTRO DEL DF INICIAL

data_frame = data_frame.merge(data_frameSGTOT, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG,PAR_4_AVG,PAR_5_AVG,AVG_PUTT,AVG_SCRAMBLING,AVG_SG_APPROACH,AVG_SG_ATG,AVG_SG_PUTTING,AVG_SG_TOTAL
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96,3.96,4.46,1.733,62.98,0.717,0.216,0.331,2.098
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01,3.99,4.54,1.720,59.95,0.315,0.147,0.429,1.253
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05,3.98,4.54,1.747,63.81,0.459,0.353,0.764,1.599
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03,3.99,4.45,1.740,59.20,0.291,-0.085,0.456,1.823
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05,3.95,4.52,1.746,67.30,0.486,0.363,0.402,1.820

In [517]:
# VAMOS A INCORPORAR LA ESTADISTICA STROKES GAINED TEE TO GREEN

import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\SG TTG 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameSGTTG = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameSGTTG.head()

,RANK,MOVEMENT,PLAYER_ID,PLAYER,AVG,SG:OTT,SG:APR,SG:ARG,MEASURED ROUNDS
0,1,0,46970,Jon Rahm,1.767,0.834,0.717,0.216,64
1,2,0,50525,Collin Morikawa,1.528,0.281,1.170,0.077,66
2,3,0,35450,Patrick Cantlay,1.418,0.569,0.486,0.363,68
3,3,0,33448,Justin Thomas,1.418,0.235,0.887,0.296,68
4,5,0,47959,Bryson DeChambeau,1.367,1.162,0.291,-0.085,68

In [518]:
data_frameSGTTG

data_frameSGTTG.rename(columns={'AVG': 'AVG_SG_TTG'}, inplace=True)
data_frameSGTTG = data_frameSGTTG[['PLAYER_ID', 'AVG_SG_TTG']]

In [519]:
# ENSAMBLAMOS EL AVG_SG_TTG DENTRO DEL DF INICIAL

data_frame = data_frame.merge(data_frameSGTTG, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,PAR_3_AVG,PAR_4_AVG,PAR_5_AVG,AVG_PUTT,AVG_SCRAMBLING,AVG_SG_APPROACH,AVG_SG_ATG,AVG_SG_PUTTING,AVG_SG_TOTAL,AVG_SG_TTG
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,2.96,3.96,4.46,1.733,62.98,0.717,0.216,0.331,2.098,1.767
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,3.01,3.99,4.54,1.720,59.95,0.315,0.147,0.429,1.253,0.824
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,3.05,3.98,4.54,1.747,63.81,0.459,0.353,0.764,1.599,0.835
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,3.03,3.99,4.45,1.740,59.20,0.291,-0.085,0.456,1.823,1.367
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,3.05,3.95,4.52,1.746,67.30,0.486,0.363,0.402,1.820,1.418

In [520]:
# VAMOS A INCORPORAR LA ESTADISTICA TOP 10 
import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\TOP 10 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameTOP10 = pd.read_csv(csv_file_path)

# Mostrar las primeras filas del DataFrame
data_frameTOP10.head()

   RANK  MOVEMENT  PLAYER_ID             PLAYER  TOP 10  1ST  2ND  3RD
0     1         0      46970           Jon Rahm      15  1.0  2.0  2.0
1     2         0      45526      Abraham Ancer       9  1.0  1.0  NaN
2     2         0      47959  Bryson DeChambeau       9  2.0  1.0  1.0
3     2         0      30925     Dustin Johnson       9  1.0  1.0  NaN
4     2         0      34046      Jordan Spieth       9  1.0  2.0  2.0

In [521]:
data_frameTOP10.rename(columns={'TOP 10': 'TOP10'}, inplace=True)
data_frameTOP10 = data_frameTOP10[['PLAYER_ID', 'TOP10']]

In [522]:
# ENSAMBLAMOS EL AVG_SG_TTG DENTRO DEL DF INICIAL

data_frame = data_frame.merge(data_frameTOP10, on='PLAYER_ID', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,...,PAR_4_AVG,PAR_5_AVG,AVG_PUTT,AVG_SCRAMBLING,AVG_SG_APPROACH,AVG_SG_ATG,AVG_SG_PUTTING,AVG_SG_TOTAL,AVG_SG_TTG,TOP10
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,...,3.96,4.46,1.733,62.98,0.717,0.216,0.331,2.098,1.767,15.0
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,...,3.99,4.54,1.720,59.95,0.315,0.147,0.429,1.253,0.824,9.0
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,...,3.98,4.54,1.747,63.81,0.459,0.353,0.764,1.599,0.835,8.0
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,...,3.99,4.45,1.740,59.20,0.291,-0.085,0.456,1.823,1.367,9.0
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,...,3.95,4.52,1.746,67.30,0.486,0.363,0.402,1.820,1.418,7.0

In [523]:
# VAMOS A INCORPORAR LA ESTADISTICA  WININGS
import pandas as pd

# Ruta al archivo CSV
csv_file_path = r'C:\Users\kikot\Desktop\TFM GOLF\2020\WINNERS 2020.csv'

# Cargar el archivo CSV en un DataFrame
data_frameTOP10 = pd.read_csv(csv_file_path)

# Cambiar nombres de columnas usando la funci√≥n rename
data_frameTOP10.rename(columns={'Nombre': 'PLAYER_NAME', 'Victorias': 'WINS'}, inplace=True)

# Mostrar las primeras filas del DataFrame
data_frameTOP10.head()

         PLAYER_NAME  WINS
0    Patrick Cantlay     4
1           Jon Rahm     3
2  Bryson DeChambeau     2
3     Dustin Johnson     2
4       Jason Kokrak     2

In [524]:
data_frame = data_frame.merge(data_frameTOP10, on='PLAYER_NAME', how='left')
data_frame.head()

,PLAYER_ID,PLAYER_NAME,AVG_TOTAL_FOR_ROUND,TOTAL_ROUNDS,YEAR,AVG_DRIVER_DISTANCE,AVG_FAIRWAY,FEDEX_POINTS,AVG_GIR,MONEY,...,PAR_5_AVG,AVG_PUTT,AVG_SCRAMBLING,AVG_SG_APPROACH,AVG_SG_ATG,AVG_SG_PUTTING,AVG_SG_TOTAL,AVG_SG_TTG,TOP10,WINS
0,46970,Jon Rahm,69.300,77,2020,309.0,62.53,2003.0,71.93,$7705933,...,4.46,1.733,62.98,0.717,0.216,0.331,2.098,1.767,15.0,3.0
1,30925,Dustin Johnson,69.619,72,2020,312.9,57.03,1510.0,66.67,$5001136,...,4.54,1.720,59.95,0.315,0.147,0.429,1.253,0.824,9.0,2.0
2,26329,Louis Oosthuizen,69.714,74,2020,297.8,62.40,1877.0,67.64,$6306679,...,4.54,1.747,63.81,0.459,0.353,0.764,1.599,0.835,8.0,NaN
3,47959,Bryson DeChambeau,69.728,80,2020,323.7,54.78,1910.0,67.15,$7426415,...,4.45,1.740,59.20,0.291,-0.085,0.456,1.823,1.367,9.0,2.0
4,35450,Patrick Cantlay,69.736,78,2020,302.8,60.21,2056.0,70.16,$7638805,...,4.52,1.746,67.30,0.486,0.363,0.402,1.820,1.418,7.0,4.0

In [525]:
# Define el orden deseado de las columnas
column_order = ['PLAYER_ID', 'PLAYER_NAME', 'TOTAL_ROUNDS', 'AVG_FAIRWAY', 'AVG_SCRAMBLING', 'AVG_TOTAL_FOR_ROUND', 'AVG_DRIVER_DISTANCE','AVG_SG_APPROACH', 'AVG_GIR', 'AVG_PUTT', 'AVG_SG_ATG', 'AVG_SG_PUTTING', 'AVG_SG_TOTAL', 'AVG_SG_TTG','PAR_5_AVG','PAR_4_AVG','PAR_3_AVG', 'WINS', 'TOP10', 'YEAR', 'FEDEX_POINTS', 'MONEY']

# Reordena las columnas en el DataFrame
data_frame = data_frame[column_order]

# Mostrar el DataFrame con las columnas ordenadas
data_frame.head()

,PLAYER_ID,PLAYER_NAME,TOTAL_ROUNDS,AVG_FAIRWAY,AVG_SCRAMBLING,AVG_TOTAL_FOR_ROUND,AVG_DRIVER_DISTANCE,AVG_SG_APPROACH,AVG_GIR,AVG_PUTT,...,AVG_SG_TOTAL,AVG_SG_TTG,PAR_5_AVG,PAR_4_AVG,PAR_3_AVG,WINS,TOP10,YEAR,FEDEX_POINTS,MONEY
0,46970,Jon Rahm,77,62.53,62.98,69.300,309.0,0.717,71.93,1.733,...,2.098,1.767,4.46,3.96,2.96,3.0,15.0,2020,2003.0,$7705933
1,30925,Dustin Johnson,72,57.03,59.95,69.619,312.9,0.315,66.67,1.720,...,1.253,0.824,4.54,3.99,3.01,2.0,9.0,2020,1510.0,$5001136
2,26329,Louis Oosthuizen,74,62.40,63.81,69.714,297.8,0.459,67.64,1.747,...,1.599,0.835,4.54,3.98,3.05,NaN,8.0,2020,1877.0,$6306679
3,47959,Bryson DeChambeau,80,54.78,59.20,69.728,323.7,0.291,67.15,1.740,...,1.823,1.367,4.45,3.99,3.03,2.0,9.0,2020,1910.0,$7426415
4,35450,Patrick Cantlay,78,60.21,67.30,69.736,302.8,0.486,70.16,1.746,...,1.820,1.418,4.52,3.95,3.05,4.0,7.0,2020,2056.0,$7638805

In [526]:
num_rows, num_columns = data_frame.shape
print("N√∫mero de filas:", num_rows)
print("N√∫mero de columnas:", num_columns)

N√∫mero de filas: 196
N√∫mero de columnas: 22

In [527]:
# Contar el n√∫mero de valores NaN en cada columna
num_nans_per_column = data_frame.isna().sum()

# Mostrar el n√∫mero de valores NaN por columna
print(num_nans_per_column)

PLAYER_ID                0
PLAYER_NAME              0
TOTAL_ROUNDS             0
AVG_FAIRWAY              0
AVG_SCRAMBLING           0
AVG_TOTAL_FOR_ROUND      0
AVG_DRIVER_DISTANCE      0
AVG_SG_APPROACH          0
AVG_GIR                  0
AVG_PUTT                 0
AVG_SG_ATG               0
AVG_SG_PUTTING           0
AVG_SG_TOTAL             0
AVG_SG_TTG               0
PAR_5_AVG                0
PAR_4_AVG                0
PAR_3_AVG                0
WINS                   164
TOP10                   35
YEAR                     0
FEDEX_POINTS             1
MONEY                    0
dtype: int64

In [528]:
# Reemplazar los valores NaN por 0 en todo el DataFrame
df_filled = data_frame.fillna(0)

# Mostrar el DataFrame con los valores NaN reemplazados por 0
print(df_filled)

     PLAYER_ID        PLAYER_NAME  TOTAL_ROUNDS  AVG_FAIRWAY  AVG_SCRAMBLING  \
0        46970           Jon Rahm            77        62.53           62.98
1        30925     Dustin Johnson            72        57.03           59.95
2        26329   Louis Oosthuizen            74        62.40           63.81
3        47959  Bryson DeChambeau            80        54.78           59.20
4        35450    Patrick Cantlay            78        60.21           67.30
..         ...                ...           ...          ...             ...
191      27095        Nick Watney            54        53.91           56.38
192      39975        Michael Kim            69        48.49           56.73
193      34213     Grayson Murray            49        50.10           46.67
194      35617     Martin Trainer            59        50.46           56.24
195      24781       Hunter Mahan            57        56.97           53.90

     AVG_TOTAL_FOR_ROUND  AVG_DRIVER_DISTANCE  AVG_SG_APPROACH  AVG_GIR  \
0                 69.300                309.0            0.717    71.93
1                 69.619                312.9            0.315    66.67
2                 69.714                297.8            0.459    67.64
3                 69.728                323.7            0.291    67.15
4                 69.736                302.8            0.486    70.16
..                   ...                  ...              ...      ...
191               72.787                299.3           -0.205    65.33
192               72.809                293.2            0.022    61.11
193               73.115                305.5           -0.260    62.59
194               73.131                303.6           -1.458    55.46
195               73.201                296.2           -1.601    57.50

     AVG_PUTT  ...  AVG_SG_TOTAL  AVG_SG_TTG  PAR_5_AVG  PAR_4_AVG  PAR_3_AVG  \
0       1.733  ...         2.098       1.767       4.46       3.96       2.96
1       1.720  ...         1.253       0.824       4.54       3.99       3.01
2       1.747  ...         1.599       0.835       4.54       3.98       3.05
3       1.740  ...         1.823       1.367       4.45       3.99       3.03
4       1.746  ...         1.820       1.418       4.52       3.95       3.05
..        ...  ...           ...         ...        ...        ...        ...
191     1.824  ...        -1.442      -0.983       4.81       4.07       3.13
192     1.829  ...        -1.369      -1.209       4.71       4.16       3.03
193     1.801  ...        -2.108      -0.846       4.75       4.13       3.18
194     1.784  ...        -1.781      -2.057       4.74       4.13       3.20
195     1.773  ...        -1.788      -2.279       4.81       4.10       3.25

     WINS  TOP10  YEAR  FEDEX_POINTS     MONEY
0     3.0   15.0  2020        2003.0  $7705933
1     2.0    9.0  2020        1510.0  $5001136
2     0.0    8.0  2020        1877.0  $6306679
3     2.0    9.0  2020        1910.0  $7426415
4     4.0    7.0  2020        2056.0  $7638805
..    ...    ...   ...           ...       ...
191   0.0    0.0  2020          89.0   $159576
192   0.0    0.0  2020          44.0   $132613
193   0.0    1.0  2020         122.0   $255130
194   0.0    0.0  2020          25.0    $60284
195   0.0    0.0  2020          18.0    $58600

[196 rows x 22 columns]

In [529]:
# Reemplazar los valores NaN por 0 en todo el DataFrame
data_frame = data_frame.fillna(0)

# Mostrar el DataFrame con los valores NaN reemplazados por 0
print(data_frame)

     PLAYER_ID        PLAYER_NAME  TOTAL_ROUNDS  AVG_FAIRWAY  AVG_SCRAMBLING  \
0        46970           Jon Rahm            77        62.53           62.98
1        30925     Dustin Johnson            72        57.03           59.95
2        26329   Louis Oosthuizen            74        62.40           63.81
3        47959  Bryson DeChambeau            80        54.78           59.20
4        35450    Patrick Cantlay            78        60.21           67.30
..         ...                ...           ...          ...             ...
191      27095        Nick Watney            54        53.91           56.38
192      39975        Michael Kim            69        48.49           56.73
193      34213     Grayson Murray            49        50.10           46.67
194      35617     Martin Trainer            59        50.46           56.24
195      24781       Hunter Mahan            57        56.97           53.90

     AVG_TOTAL_FOR_ROUND  AVG_DRIVER_DISTANCE  AVG_SG_APPROACH  AVG_GIR  \
0                 69.300                309.0            0.717    71.93
1                 69.619                312.9            0.315    66.67
2                 69.714                297.8            0.459    67.64
3                 69.728                323.7            0.291    67.15
4                 69.736                302.8            0.486    70.16
..                   ...                  ...              ...      ...
191               72.787                299.3           -0.205    65.33
192               72.809                293.2            0.022    61.11
193               73.115                305.5           -0.260    62.59
194               73.131                303.6           -1.458    55.46
195               73.201                296.2           -1.601    57.50

     AVG_PUTT  ...  AVG_SG_TOTAL  AVG_SG_TTG  PAR_5_AVG  PAR_4_AVG  PAR_3_AVG  \
0       1.733  ...         2.098       1.767       4.46       3.96       2.96
1       1.720  ...         1.253       0.824       4.54       3.99       3.01
2       1.747  ...         1.599       0.835       4.54       3.98       3.05
3       1.740  ...         1.823       1.367       4.45       3.99       3.03
4       1.746  ...         1.820       1.418       4.52       3.95       3.05
..        ...  ...           ...         ...        ...        ...        ...
191     1.824  ...        -1.442      -0.983       4.81       4.07       3.13
192     1.829  ...        -1.369      -1.209       4.71       4.16       3.03
193     1.801  ...        -2.108      -0.846       4.75       4.13       3.18
194     1.784  ...        -1.781      -2.057       4.74       4.13       3.20
195     1.773  ...        -1.788      -2.279       4.81       4.10       3.25

     WINS  TOP10  YEAR  FEDEX_POINTS     MONEY
0     3.0   15.0  2020        2003.0  $7705933
1     2.0    9.0  2020        1510.0  $5001136
2     0.0    8.0  2020        1877.0  $6306679
3     2.0    9.0  2020        1910.0  $7426415
4     4.0    7.0  2020        2056.0  $7638805
..    ...    ...   ...           ...       ...
191   0.0    0.0  2020          89.0   $159576
192   0.0    0.0  2020          44.0   $132613
193   0.0    1.0  2020         122.0   $255130
194   0.0    0.0  2020          25.0    $60284
195   0.0    0.0  2020          18.0    $58600

[196 rows x 22 columns]

In [530]:
data_frame2020 = data_frame

In [531]:
# Ruta para guardar el archivo CSV
ruta_guardado = r'C:\Users\kikot\Desktop\TFM GOLF\data_frame2020.csv'

# Exportar el DataFrame a un archivo CSV en la ruta especificada
data_frame2020.to_csv(ruta_guardado, index=False)

In [532]:
# Contar el n√∫mero de valores NaN en cada columna
num_nans_per_column = data_frame.isna().sum()

# Mostrar el n√∫mero de valores NaN por columna
print(num_nans_per_column)

PLAYER_ID              0
PLAYER_NAME            0
TOTAL_ROUNDS           0
AVG_FAIRWAY            0
AVG_SCRAMBLING         0
AVG_TOTAL_FOR_ROUND    0
AVG_DRIVER_DISTANCE    0
AVG_SG_APPROACH        0
AVG_GIR                0
AVG_PUTT               0
AVG_SG_ATG             0
AVG_SG_PUTTING         0
AVG_SG_TOTAL           0
AVG_SG_TTG             0
PAR_5_AVG              0
PAR_4_AVG              0
PAR_3_AVG              0
WINS                   0
TOP10                  0
YEAR                   0
FEDEX_POINTS           0
MONEY                  0
dtype: int64